apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Software\Docker\kompose-windows-amd64.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: monitor
    spec:
      containers:
      - env:
        - name: io.zeebe.monitor.connectionString
          value: zeebe:26500
        - name: io.zeebe.monitor.hazelcast.connection
          value: zeebe:5701
        - name: spring.datasource.url
          value: jdbc:h2:tcp://db:1521/zeebe-monitor
        image: camunda/zeebe-simple-monitor:latest
        name: zeebe_monitor
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
