apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Software\Docker\kompose-windows-amd64.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: operate
  name: operate
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: operate
    spec:
      containers:
      - image: camunda/operate:1.0.0-alpha11
        name: operate
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/operate/config/application.yml
          name: operate-claim0
      restartPolicy: Always
      volumes:
      - name: operate-claim0
        persistentVolumeClaim:
          claimName: operate-claim0
status: {}
