apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Software\Docker\kompose-windows-amd64.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: operate
  name: operate
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: operate
status:
  loadBalancer: {}
