apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Software\Docker\kompose-windows-amd64.exe convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: zeebe
  name: zeebe
spec:
  ports:
  - name: "26500"
    port: 26500
    targetPort: 26500
  - name: "5701"
    port: 5701
    targetPort: 5701
  selector:
    io.kompose.service: zeebe
status:
  loadBalancer: {}
